name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run npm steps
      run: |
        npm install
        npm run eslint
        npm run abaplint
        npm run merge
        npm run merge.ci
    - name: deploy-merged-build
      if: github.ref == 'refs/heads/master' && github.repository == 'larshp/abapGit'
      env:
        GITHUB_API_KEY: ${{ secrets.MY_TOKEN }}
      run: ./ci/deploy-merged-build.sh
    - name: deploy-release-tag
      if: github.ref == 'refs/heads/master' && github.repository == 'larshp/abapGit'
      env:
        GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: ./ci/deploy-release-tag.sh
